### PR TITLE
Update to 1.1.2

### PR DESCRIPTION
**Pull request by adrianchia**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dpryan79** [comment]
@conda-forge/keras-preprocessing Can this get merged? It's blocking stuff on Bioconda.

**Comment by h-vetinari** [comment]
Also interested in this for trying to get https://github.com/conda-forge/tensorflow-feedstock/pull/110 working

**Comment by dpryan79** [comment]
@conda-forge/core The maintainer isn't responsive at the moment, could one of you merge this?

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
Would be nice if someone could fix the lint issues and step up as a maintainer

**Comment by h-vetinari** [comment]
> Would be nice if someone could fix the lint issues and step up as a maintainer

I'd be up for it: #14

**Comment by h-vetinari** [comment]
Thanks @adrianchia @dpryan79 @xhochy

**Comment by h-vetinari** [comment]
Also leaving this as a reference why the bot didn't pick this up: https://github.com/keras-team/keras-preprocessing/issues/305

**Pull request merged**
